//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManajemenBarang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbStokEntities : DbContext
    {
        public dbStokEntities()
            : base("name=dbStokEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barang> Barangs { get; set; }
        public virtual DbSet<BarangKeluar> BarangKeluars { get; set; }
        public virtual DbSet<BarangMasuk> BarangMasuks { get; set; }
        public virtual DbSet<BarangReturn> BarangReturns { get; set; }
        public virtual DbSet<Kategori> Kategoris { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
    
        public virtual int AddUser(Nullable<int> id_user, string username, string password, Nullable<int> status_user, string nama_supplier, string alamat_supplier, string telp_supplier)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var status_userParameter = status_user.HasValue ?
                new ObjectParameter("status_user", status_user) :
                new ObjectParameter("status_user", typeof(int));
    
            var nama_supplierParameter = nama_supplier != null ?
                new ObjectParameter("nama_supplier", nama_supplier) :
                new ObjectParameter("nama_supplier", typeof(string));
    
            var alamat_supplierParameter = alamat_supplier != null ?
                new ObjectParameter("alamat_supplier", alamat_supplier) :
                new ObjectParameter("alamat_supplier", typeof(string));
    
            var telp_supplierParameter = telp_supplier != null ?
                new ObjectParameter("telp_supplier", telp_supplier) :
                new ObjectParameter("telp_supplier", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddUser", id_userParameter, usernameParameter, passwordParameter, status_userParameter, nama_supplierParameter, alamat_supplierParameter, telp_supplierParameter);
        }
    
        public virtual int AddSupplier(Nullable<int> id_user, string nama_supplier, string alamat_supplier, string telp_supplier)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            var nama_supplierParameter = nama_supplier != null ?
                new ObjectParameter("nama_supplier", nama_supplier) :
                new ObjectParameter("nama_supplier", typeof(string));
    
            var alamat_supplierParameter = alamat_supplier != null ?
                new ObjectParameter("alamat_supplier", alamat_supplier) :
                new ObjectParameter("alamat_supplier", typeof(string));
    
            var telp_supplierParameter = telp_supplier != null ?
                new ObjectParameter("telp_supplier", telp_supplier) :
                new ObjectParameter("telp_supplier", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddSupplier", id_userParameter, nama_supplierParameter, alamat_supplierParameter, telp_supplierParameter);
        }
    
        public virtual ObjectResult<GetUsup_Result> GetUsup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsup_Result>("GetUsup");
        }
    }
}
