//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManajemenBarang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategori
    {
        public int id_kategori { get; set; }
        public string nama_kategori { get; set; }
        public string deskripsi { get; set; }
    }
}
