//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManajemenBarang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int id_supplier { get; set; }
        public int id_user { get; set; }
        public string nama_supplier { get; set; }
        public string alamat_supplier { get; set; }
        public string telp_supplier { get; set; }
    }
}
